### ISSUE TITLE
34-3: Kaupan lisätiedot (infosivu?), jossa omistajat, perustamisvuosi ja Y-tunnus.

### ISSUE THREAD

**Issue by Maajoo** [SyntaxSynergy/k24TiimiNROFrontEnd#5]

**Comment by SophiaDun** [comment]
Sivuston Navigointi palkista löytyy Meistä nappi joka vie http://localhost:5173/Meista sivulle.
Sivustossa näkyy tieto omistajista, perustamisvuodesta, y-tunnus sekä tarina yrityksen missiosta.
Hyvin hoidettu!
