### ISSUE TITLE
46-3 Sivu, jossa voin rekisteröityä front end appin käyttäjäksi

### ISSUE THREAD

**Issue by Maajoo** [SyntaxSynergy/k24TiimiNROFrontEnd#8]

**Comment by SophiaDun** [comment]
**Testaus vaiheet:**

1.Nav palkissa sijaitsee Rekisteröinti nappi, painoin nappia.

2.Rekisteröinti sivussa  syötin käyttäjänimkeksi sophia ja salasanaksi sophia ja painoin register nappia.

3.Menin tarkastamaan, että tieto on siirtynyt oikein tietokantaan osoitteetsa:
https://syntaxbackend-f811444e58ce.herokuapp.com/api/users

4.Käyttäjän tiedot oli onnistuneesti siirtynyt tietokantaan, hienoa työtä!!
